export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_ERROR = 'ADD_POST_ERROR'

export const FETCH_PAGES_SUCCESS = 'FETCH_PAGES_SUCCESS'
export const FETCH_PAGES_ERROR = 'FETCH_PAGES_ERROR'

export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS'
export const FETCH_FIELDS_ERROR = 'FETCH_FIELDS_ERROR'

export const FETCH_SOUNDS_SUCCESS = 'FETCH_SOUNDS_SUCCESS'
export const FETCH_SOUNDS_ERROR = 'FETCH_SOUNDS_ERROR'

export const FETCH_SC_SUCCESS = 'FETCH_SC_SUCCESS'
export const FETCH_SC_ERROR = 'FETCH_SC_ERROR'

export const FETCH_SC_TRACKS_SUCCESS = 'FETCH_SC_TRACKS_SUCCESS'
export const FETCH_SC_TRACKS_ERROR = 'FETCH_SC_TRACKS_ERROR'
