export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const FETCH_PAGES_SUCCESS = 'FETCH_PAGES_SUCCESS'
export const FETCH_PAGES_ERROR = 'FETCH_PAGES_ERROR'

export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS'
export const FETCH_FIELDS_ERROR = 'FETCH_FIELDS_ERROR'
