const aboutText = [
  '://N O p r o j e k t',
  'a collection of interdisciplinary computers/ bound by ties that',
  'are under NO control* This conglomerate of binary and non§binary',
  'characters create sound/ visual/ and conversational arts in',
  'order to reach an aesthetic proposal that diverts our',
  'contemporary time*',
  '',
  '',
  '',
  'Proposal = ',
  'a e s t h e t i c d i m e n s i o n o f c a p i t a l i s m',
  'as questioned by the philosopher',
  'Byung Chul Han',
  'in his book ^Saving Beauty^*',
  '',
  '',
  '',
  '://',
  'Beauty today is a paradox* The cult of beauty is ubiquitous but',
  'it has lost its transcendence and become little more than an',
  'aspect of consumerism the sublime and unsettling aspects of',
  'beauty have given way to corporeal pleasures and ^likes^/',
  'resulting in a species of the = pornography of beauty*',
  '',
  '',
  'NO also challenges = p r o p e r t y and the idea of art as',
  'belonging to someone or something instead of itself*',
  '',
  'Proudhon challenges ownership in his book = ^WHAT IS PROPERTY^*',
  '',
  'He claims that ^La propriété, c^est le vol// (Property is',
  'theft//)^/ as an inquiry into the principle of rights and of the government*',
  '',
  '',
  '',
  '**Is an artwork an artist^s property &',
  '**Can an artwork be sold to become someone else^s property &',
  '**Can an idea belong to someone &',
  '**If a work is intervened or worked by other people who owns it',
  '$',
  '',
  '',
  '',
  'A NO a r t i s t is but a window to let sunlight through* ',
  'It^s job is to be translucent/ not revel in the sun^s creative',
  'power*',
  '',
  '',
  'NO IS establishes the sound wing of NO*',
  'We explore forms of sound and time based experimentation*',
  'By studying noise/ cacophony/ cadence/ rhythm/ acoustic and',
  'electric sound sources/ the NO IS attempts to decipher what',
  'cannot be put into words*',
  'Sounds which move us whether in pleasure or in horror combine in',
  'order to expand our',
  'view of sonic culture*',
  '',
  '',
  '',
  'NO IS will be improvising with an electro§acoustic set§up',
  'featuring the double§bass and modular synthesis* Though today we',
  'will be improvising/ the first NO album titled/ ^Abrazar el',
  'Aire/ Apretar los Dientes^ (^Hug the Air/ Grit your Teeth^) will',
  'be released in the upcoming months as a collaboration with',
  'Madrid-based Venezuelan author/ Domenico Chiappe who is a leader',
  'in the exploration of multi-media literature* His latest',
  'synonymously titled book/ features an online interactive 3D',
  'space as the ^casing^ of the piece*',
  '',
  '',
  '',
  'FB:// NO',
  'IG:// NO.Projekt',
  'TW:// NOPROJEKT',
  '',
  '',
  '',
  '“...In this methodology, if something is made based on a',
  'separate idea, the result is a representation of the',
  'characteristics not of a material but of an act. Thus, without',
  'constantly changing materials, we may change ideas and the ones',
  'who think them. Just as things have certain characteristics, our',
  'gestures and acts also have definitive characteristics, which',
  'differ from person to person. Even if the same thing is made',
  'from the same material and the same method, we can still clearly',
  'see a different act. Only at this point can we discuss whether',
  'each case involves thought at all. We then realize that the',
  'limits of act are defined not by those of things but by those of',
  'thought. We did not question when new materials revealed the',
  'same worn and overused ideas. But well-used materials expose the',
  'limits of action and confirm that ideas must be isolated from',
  'one another and move to an invisible dimension.”',
  '',
  '-Badiou “The Age of the Poets”',
]
export default aboutText
